import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        bg: '#0a0a0a',
        s1: '#111111',
        s2: '#1a1a1a',
        s3: '#222222',
        s4: '#2a2a2a',
        border: '#2a2a2a',
        'border-hover': 'rgba(255,255,255,0.20)',
        'border-focus': '#00e5ff',
        text: '#e0e0e0',
        dim: '#888888',
        muted: '#555555',
        faint: 'rgba(255,255,255,0.10)',
        amber: {
          DEFAULT: '#f5a623',
          dim: 'rgba(245,166,35,0.15)',
          glow: 'rgba(245,166,35,0.30)',
        },
        cyan: {
          DEFAULT: '#00e5ff',
          dim: 'rgba(0,229,255,0.15)',
          glow: 'rgba(0,229,255,0.30)',
        },
        green: '#00d4aa',
        red: '#ff4757',
        blue: '#4a9eff',
        purple: '#a78bfa',
        accent: '#4a9eff',
        accent2: '#f5a623',
        orange: '#f5a623',
        yellow: '#f5a623',
        pink: '#a78bfa',
      },
      fontSize: {
        '4xs': ['0.5rem', { lineHeight: '1.2', letterSpacing: '0.2em' }],
        '3xs': ['0.5625rem', { lineHeight: '1.2', letterSpacing: '0.15em' }],
        '2xs': ['0.625rem', { lineHeight: '1.2', letterSpacing: '0.05em' }],
      },
      fontFamily: {
        data: ['"JetBrains Mono"', '"SF Mono"', '"Fira Code"', '"Cascadia Code"', 'monospace'],
        ui: ['"Inter"', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Roboto', 'sans-serif'],
      },
      spacing: {
        'sidebar-collapsed': '48px',
        'sidebar-expanded': '200px',
        'topbar-h': '40px',
        'ticker-h': '28px',
      },
      boxShadow: {
        'glow-amber': '0 0 20px rgba(245,166,35,0.08)',
        'glow-cyan': '0 0 15px rgba(0,229,255,0.10)',
        'glow-green': '0 0 12px rgba(0,212,170,0.10)',
        'glow-red': '0 0 12px rgba(255,71,87,0.10)',
      },
      zIndex: {
        'base': '0',
        'elevated': '10',
        'dropdown': '20',
        'sidebar': '30',
        'overlay': '40',
        'modal': '50',
        'hover-preview': '90',
        'command-palette': '100',
        'toast': '110',
        'tooltip': '120',
      },
      transitionDuration: {
        'fast': '100ms',
        'normal': '200ms',
        'slow': '300ms',
        'slower': '500ms',
        'slowest': '1000ms',
      },
      transitionTimingFunction: {
        'out-expo': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'in-out-smooth': 'cubic-bezier(0.45, 0, 0.55, 1)',
        'spring': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        fadeOut: { '0%': { opacity: '1' }, '100%': { opacity: '0' } },
        slideInUp: { '0%': { opacity: '0', transform: 'translateY(8px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        slideInDown: { '0%': { opacity: '0', transform: 'translateY(-8px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        slideInLeft: { '0%': { opacity: '0', transform: 'translateX(-8px)' }, '100%': { opacity: '1', transform: 'translateX(0)' } },
        slideInRight: { '0%': { opacity: '0', transform: 'translateX(8px)' }, '100%': { opacity: '1', transform: 'translateX(0)' } },
        'ticker-scroll': { '0%': { transform: 'translateX(0)' }, '100%': { transform: 'translateX(-50%)' } },
        'pulse-glow': { '0%, 100%': { boxShadow: '0 0 0 0 rgba(245, 166, 35, 0.2)' }, '50%': { boxShadow: '0 0 12px 2px rgba(245, 166, 35, 0.15)' } },
        'pulse-glow-cyan': { '0%, 100%': { boxShadow: '0 0 0 0 rgba(0, 229, 255, 0.2)' }, '50%': { boxShadow: '0 0 12px 2px rgba(0, 229, 255, 0.15)' } },
        'count-up': { '0%': { opacity: '0', transform: 'translateY(4px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        shimmer: { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        'data-flash': { '0%, 100%': { opacity: '1' }, '50%': { opacity: '0.6' } },
        'card-hover-lift': { '0%': { transform: 'translateY(0)', boxShadow: '0 0 0 rgba(0,0,0,0)' }, '100%': { transform: 'translateY(-2px)', boxShadow: '0 8px 24px rgba(0,0,0,0.3)' } },
        'new-item-flash': { '0%': { boxShadow: '0 0 0 0 rgba(0,229,255,0.4)' }, '50%': { boxShadow: '0 0 16px 4px rgba(0,229,255,0.15)' }, '100%': { boxShadow: '0 0 0 0 rgba(0,229,255,0)' } },
        'radar-draw': { '0%': { strokeDashoffset: '300', opacity: '0' }, '50%': { opacity: '1' }, '100%': { strokeDashoffset: '0', opacity: '1' } },
        'number-counter': { '0%': { opacity: '0', transform: 'translateY(8px) scale(0.95)' }, '60%': { opacity: '1', transform: 'translateY(-1px) scale(1.02)' }, '100%': { opacity: '1', transform: 'translateY(0) scale(1)' } },
        'stagger-in': { '0%': { opacity: '0', transform: 'translateY(12px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        'page-enter': { '0%': { opacity: '0', transform: 'translateY(4px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        'page-exit': { '0%': { opacity: '1', transform: 'translateY(0)' }, '100%': { opacity: '0', transform: 'translateY(-4px)' } },
        'skeleton-pulse': { '0%, 100%': { opacity: '0.04' }, '50%': { opacity: '0.08' } },
        'cursor-blink': { '0%, 100%': { opacity: '1' }, '50%': { opacity: '0' } },
        'scan-line': { '0%': { transform: 'translateY(-100%)' }, '100%': { transform: 'translateY(100%)' } },
        'background-radar': { '0%': { transform: 'scale(0)', opacity: '0.03' }, '50%': { opacity: '0.015' }, '100%': { transform: 'scale(4)', opacity: '0' } },
      },
      animation: {
        fadeIn: 'fadeIn 200ms ease-out',
        fadeOut: 'fadeOut 200ms ease-out',
        slideInUp: 'slideInUp 200ms ease-out',
        slideInDown: 'slideInDown 200ms ease-out',
        slideInLeft: 'slideInLeft 200ms ease-out',
        slideInRight: 'slideInRight 200ms ease-out',
        'ticker-scroll': 'ticker-scroll 40s linear infinite',
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
        'pulse-glow-cyan': 'pulse-glow-cyan 2s ease-in-out infinite',
        'count-up': 'count-up 300ms ease-out',
        shimmer: 'shimmer 1.5s ease-in-out infinite',
        'data-flash': 'data-flash 0.4s ease-out',
        'card-hover-lift': 'card-hover-lift 200ms ease-out forwards',
        'new-item-flash': 'new-item-flash 1s ease-out',
        'radar-draw': 'radar-draw 1000ms ease-out forwards',
        'number-counter': 'number-counter 400ms cubic-bezier(0.34, 1.56, 0.64, 1)',
        'stagger-in': 'stagger-in 300ms ease-out both',
        'page-enter': 'page-enter 300ms ease-out',
        'page-exit': 'page-exit 200ms ease-in',
        'skeleton-pulse': 'skeleton-pulse 1.5s ease-in-out infinite',
        'cursor-blink': 'cursor-blink 1s step-end infinite',
        'background-radar': 'background-radar 60s ease-out infinite',
      },
    },
  },
  plugins: [],
}
export default config
