"""Executive PDF report generator using reportlab.

Generates weekly/monthly intelligence reports covering:
- Sponsor landscape changes
- Job market metrics
- Immigration policy updates
- Agent performance stats
"""

import io
import logging
from datetime import datetime, timezone

logger = logging.getLogger(__name__)


def generate_executive_report(
    stats: dict,
    period: str = "weekly",
) -> bytes:
    """Generate an executive PDF report.

    Parameters
    ----------
    stats : dict
        Keys: sponsor_stats, job_stats, intel_stats, agent_stats
    period : str
        Report period label (weekly/monthly)

    Returns
    -------
    bytes — PDF file content
    """
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.colors import HexColor
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=40, bottomMargin=40)
    styles = getSampleStyleSheet()

    # Custom styles
    amber = HexColor("#f5a623")
    dark_bg = HexColor("#1a1a1a")
    text_color = HexColor("#e0e0e0")

    title_style = ParagraphStyle(
        "CustomTitle", parent=styles["Title"],
        fontSize=24, textColor=amber, spaceAfter=20,
    )
    heading_style = ParagraphStyle(
        "CustomHeading", parent=styles["Heading2"],
        fontSize=14, textColor=amber, spaceBefore=20, spaceAfter=10,
    )
    body_style = ParagraphStyle(
        "CustomBody", parent=styles["Normal"],
        fontSize=10, textColor=text_color, spaceAfter=8,
    )

    elements = []

    # Title
    now = datetime.now(timezone.utc)
    elements.append(Paragraph(f"SponsorIntel {period.title()} Intelligence Report", title_style))
    elements.append(Paragraph(f"Generated: {now.strftime('%d %B %Y, %H:%M UTC')}", body_style))
    elements.append(Spacer(1, 20))

    # Sponsor Landscape
    sponsor = stats.get("sponsor_stats", {})
    elements.append(Paragraph("Sponsor Landscape", heading_style))
    sponsor_data = [
        ["Metric", "Value", "Change"],
        ["Total Active Sponsors", str(sponsor.get("total_active", "—")), sponsor.get("change_total", "—")],
        ["New This Period", str(sponsor.get("new_count", 0)), ""],
        ["Removed This Period", str(sponsor.get("removed_count", 0)), ""],
        ["Rating Changes", str(sponsor.get("rating_changes", 0)), ""],
        ["A-Rated %", f"{sponsor.get('a_rated_pct', 0):.1f}%", ""],
    ]
    t = Table(sponsor_data, colWidths=[200, 120, 100])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), amber),
        ("TEXTCOLOR", (0, 0), (-1, 0), dark_bg),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#333333")),
        ("TEXTCOLOR", (0, 1), (-1, -1), text_color),
        ("BACKGROUND", (0, 1), (-1, -1), dark_bg),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 15))

    # Job Market
    jobs = stats.get("job_stats", {})
    elements.append(Paragraph("Job Market", heading_style))
    elements.append(Paragraph(f"Active Jobs: {jobs.get('total_active', '—')}", body_style))
    elements.append(Paragraph(f"New This Period: {jobs.get('new_count', 0)}", body_style))
    elements.append(Paragraph(f"Sponsorship Likely (≥60%): {jobs.get('sponsorship_likely', 0)}", body_style))
    elements.append(Paragraph(f"Median Salary: £{jobs.get('median_salary', 0):,.0f}", body_style))
    elements.append(Spacer(1, 15))

    # Intel Summary
    intel = stats.get("intel_stats", {})
    elements.append(Paragraph("Immigration Intelligence", heading_style))
    elements.append(Paragraph(f"Total Intel Items: {intel.get('total_items', 0)}", body_style))
    elements.append(Paragraph(f"Critical/High Impact: {intel.get('critical_high', 0)}", body_style))
    if intel.get("top_topics"):
        for topic, count in intel["top_topics"].items():
            elements.append(Paragraph(f"  {topic}: {count} items", body_style))
    elements.append(Spacer(1, 15))

    # Agent Performance
    agents = stats.get("agent_stats", {})
    elements.append(Paragraph("Agent Army Performance", heading_style))
    elements.append(Paragraph(f"Total Missions: {agents.get('total_missions', 0)}", body_style))
    elements.append(Paragraph(f"Success Rate: {agents.get('success_rate', 0):.1f}%", body_style))
    elements.append(Paragraph(f"LLM Cost: ${agents.get('llm_cost', 0):.2f}", body_style))
    elements.append(Spacer(1, 20))

    # Footer
    elements.append(Paragraph("— Generated by AEGIS Supreme Commander —", body_style))
    elements.append(Paragraph("sponsorintel.london", body_style))

    doc.build(elements)
    return buffer.getvalue()


async def collect_report_stats(supabase, days: int = 7) -> dict:
    """Collect all stats needed for the executive report."""
    from datetime import timedelta
    since = (datetime.now(timezone.utc) - timedelta(days=days)).isoformat()

    stats = {"sponsor_stats": {}, "job_stats": {}, "intel_stats": {}, "agent_stats": {}}

    try:
        # Sponsor stats
        total = supabase.table("sponsors").select("*", count="exact", head=True).eq("is_active", True).execute()
        stats["sponsor_stats"]["total_active"] = total.count or 0

        a_rated = supabase.table("sponsors").select("*", count="exact", head=True).eq("is_active", True).eq("rating", "A").execute()
        total_active = stats["sponsor_stats"]["total_active"] or 1
        stats["sponsor_stats"]["a_rated_pct"] = ((a_rated.count or 0) / total_active) * 100

        changes = supabase.table("sponsor_changes").select("change_type").gte("detected_at", since).execute()
        change_data = changes.data or []
        stats["sponsor_stats"]["new_count"] = sum(1 for c in change_data if c.get("change_type") == "added")
        stats["sponsor_stats"]["removed_count"] = sum(1 for c in change_data if c.get("change_type") == "removed")
        stats["sponsor_stats"]["rating_changes"] = sum(1 for c in change_data if "rating" in (c.get("change_type") or ""))

        # Job stats
        jobs_total = supabase.table("jobs").select("*", count="exact", head=True).eq("is_active", True).execute()
        stats["job_stats"]["total_active"] = jobs_total.count or 0

        jobs_new = supabase.table("jobs").select("*", count="exact", head=True).gte("created_at", since).execute()
        stats["job_stats"]["new_count"] = jobs_new.count or 0

        # Intel stats
        intel_total = supabase.table("intel_items").select("*", count="exact", head=True).gte("created_at", since).execute()
        stats["intel_stats"]["total_items"] = intel_total.count or 0

    except Exception as e:
        logger.error(f"Report stats collection error: {e}")

    return stats
