import React,{useEffect,useRef,useState} from 'react';
import {DISCOVERY_KINDS,DISCOVERY_STATES,DISCOVERY_LIMITATION} from '../shared/discovery.js';
import './discovery-desk.css';
type Content={title:string;employer:string;location:string;observed_at:string;posted_at:string|null;posted_evidence:string;deadline:string|null;deadline_evidence:string;original_url:string;identity_url:string;identity_note:string;quote:string;state:string;reason:string;follow_up_at:string|null;job_id:string|null;duplicate_of:string|null;method:string};
type Lead={id:string;source_url:string;source_kind:string;first_recorded_at:string;revision:number;recorded_at:string;content:Content;linked_current:boolean|null;job_proof:{company:string;title:string;sponsorship:string;checked_at:string}|null};
type Summary={total:number;unresolved:number;overdue:number;changed_links:number;current_linked_jobs:number};
type List={summary:Summary;page:number;total:number;leads:Lead[]};
type Detail={lead:Lead;history:Lead[];next_before:number|null};
type Job={id:string;company:string;title:string;apply_url:string;sponsorship:string};
const when=(s:string|null)=>s?new Date(s).toLocaleString('en-GB'):'Unknown';
const label=(values:Record<string,string>,key:string)=>values[key]||key;
const blank=():Content=>({title:'',employer:'',location:'',observed_at:new Date().toISOString(),posted_at:null,posted_evidence:'',deadline:null,deadline_evidence:'',original_url:'',identity_url:'',identity_note:'',quote:'',state:'pending',reason:'',follow_up_at:new Date(Date.now()+3*86400000).toISOString(),job_id:null,duplicate_of:null,method:'agent_assisted'});
async function api(path='',body?:unknown){const response=await fetch('/api/admin/discovery'+path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});let result;try{result=await response.json();}catch{throw Object.assign(Error('The server response was incomplete. Check the saved record before changing it.'),{uncertain:!!body});}if(!response.ok)throw Object.assign(Error(result.error||'Could not load discovery records.'),{status:response.status,existing_id:result.existing_id,uncertain:!!body&&response.status>=500});return result;}
function DateInput({label:valueLabel,value,onChange,required=false}:{label:string;value:string|null;onChange:(s:string|null)=>void;required?:boolean}){
 const local=value?new Date(Date.parse(value)-new Date(value).getTimezoneOffset()*60000).toISOString().slice(0,16):'';
 return <label>{valueLabel}<input type="datetime-local" required={required} value={local} onInput={e=>onChange(e.currentTarget.value?new Date(e.currentTarget.value).toISOString():null)} onChange={e=>onChange(e.target.value?new Date(e.target.value).toISOString():null)}/></label>;
}
export function DiscoveryDesk(){
 const [data,setData]=useState<List|null>(null),[state,setState]=useState(''),[query,setQuery]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(1),[detail,setDetail]=useState<Detail|null>(null),[editing,setEditing]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const generation=useRef(0);
 async function load(){const n=++generation.current;setLoading(true);try{const r=await api(`?state=${encodeURIComponent(state)}&q=${encodeURIComponent(search)}&page=${page}`);if(n===generation.current){setData(r);setError('');}}catch(e){if(n===generation.current)setError((e as Error).message);}finally{if(n===generation.current)setLoading(false);}}
 useEffect(()=>{void load();return()=>{generation.current++;};},[state,search,page]);
 async function open(id:string){setLoading(true);setError('');try{setDetail(await api('/'+id));setEditing(true);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 async function older(){if(!detail?.next_before)return;setLoading(true);try{const r:Detail=await api(`/${detail.lead.id}?before=${detail.next_before}`);setDetail({...detail,history:[...detail.history,...r.history],next_before:r.next_before});}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 return <details className="career-panel discovery-desk"><summary><span>Discovery queue</span><small>{data?`${data.summary.unresolved} to review · ${data.summary.current_linked_jobs} current linked jobs`:'Private sourcing leads'}</small></summary>
  <p>Keep company adverts and recruiting posts together. Review their original evidence, record a decision, and retain the route from a lead to a published opportunity.</p>
  {error&&<p role="alert" className="career-error">{error}</p>}
  {data&&<div className="discovery-metrics">{[['Retained leads',data.summary.total],['Awaiting review',data.summary.unresolved],['Overdue reviews',data.summary.overdue],['Changed job links',data.summary.changed_links],['Current linked jobs',data.summary.current_linked_jobs]].map(([name,n])=><div key={name}><strong>{n}</strong><span>{name}</span></div>)}</div>}
  <form className="discovery-toolbar" onSubmit={e=>{e.preventDefault();setPage(1);setSearch(query);}}><label>Find a lead<input maxLength={120} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Employer, role or source link"/></label><label>Review state<select value={state} onChange={e=>{setState(e.target.value);setPage(1);}}><option value="">All decisions</option>{Object.entries(DISCOVERY_STATES).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label><button className="secondary-button" disabled={loading}>Search leads</button><button type="button" className="secondary-button" disabled={loading} onClick={()=>void load()}>Refresh queue</button><button type="button" className="primary-button" disabled={loading} onClick={()=>{setDetail(null);setEditing(true);}}>Add a sourcing lead</button></form>
  {editing&&<DiscoveryForm key={detail?`${detail.lead.id}:${detail.lead.revision}`:'new'} lead={detail?.lead||null} onOpen={open} onSaved={async id=>{await open(id);await load();}} onClose={()=>setEditing(false)}/>}
  {editing&&detail&&<details className="discovery-history"><summary>Preserved review history · {detail.lead.revision} decisions</summary>{detail.history.map(r=><article key={r.revision}><h4>Revision {r.revision} · {label(DISCOVERY_STATES,r.content.state)}</h4><p className="fine-print">Recorded {when(r.recorded_at)} · {r.content.method==='agent_assisted'?'Agent-assisted, through the owner account':'Owner-recorded'}</p><p>{r.content.reason}</p><blockquote>{r.content.quote||'No sponsorship quotation recorded.'}</blockquote><p>Observed {when(r.content.observed_at)} · Original posting {when(r.content.posted_at)} · Follow-up {when(r.content.follow_up_at)}</p>{r.content.original_url&&<a href={r.content.original_url} target="_blank" rel="noopener noreferrer">Retained original link</a>}<details><summary>Full recorded evidence</summary><dl>{Object.entries(r.content).filter(([k])=>!['reason','quote'].includes(k)).map(([k,v])=><React.Fragment key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{v||'Not recorded'}</dd></React.Fragment>)}</dl></details></article>)}{detail.next_before&&<button className="secondary-button" disabled={loading} onClick={()=>void older()}>Load earlier decisions</button>}</details>}
  <div className="discovery-list">{data?.leads.map(lead=><article key={lead.id}><div><span className="eyebrow">{label(DISCOVERY_KINDS,lead.source_kind)}</span><h3>{lead.content.title}</h3><p>{lead.content.employer||'Employer not established'} · {lead.content.location||'Location unknown'}</p></div><p><strong>{label(DISCOVERY_STATES,lead.content.state)}</strong>{lead.linked_current===false&&' · Published evidence changed or unavailable'}</p><p>{lead.content.reason}</p>{lead.content.quote&&<blockquote>{lead.content.quote}</blockquote>}<p className="fine-print">Observed {when(lead.content.observed_at)} · Recorded {when(lead.first_recorded_at)}{lead.content.follow_up_at&&` · Follow-up ${when(lead.content.follow_up_at)}`}</p><div className="discovery-actions"><a href={lead.source_url} target="_blank" rel="noopener noreferrer">Open source</a>{lead.content.job_id&&<a href={'/jobs/'+lead.content.job_id} target="_blank" rel="noopener noreferrer">Linked job</a>}<button className="secondary-button" disabled={loading} onClick={()=>void open(lead.id)}>Review lead</button></div></article>)}</div>
  {data&&!data.leads.length&&<p>No matching leads. Newly found sources can be retained here before any publication decision.</p>}
  {data&&data.total>25&&<div className="discovery-actions"><button className="secondary-button" disabled={loading||page===1} onClick={()=>setPage(page-1)}>Previous leads</button><span>Page {page} of {Math.ceil(data.total/25)}</span><button className="secondary-button" disabled={loading||page*25>=data.total} onClick={()=>setPage(page+1)}>Next leads</button></div>}
  <p className="fine-print">{DISCOVERY_LIMITATION}</p>
 </details>;
}
function DiscoveryForm({lead,onSaved,onOpen,onClose}:{lead:Lead|null;onSaved:(id:string)=>Promise<void>;onOpen:(id:string)=>Promise<void>;onClose:()=>void}){
 const [content,setContent]=useState<Content>(lead?.content||blank()),[url,setUrl]=useState(lead?.source_url||''),[kind,setKind]=useState(lead?.source_kind||'linkedin_post'),[jobQuery,setJobQuery]=useState(lead?.content.employer||''),[jobs,setJobs]=useState<Job[]>([]),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[error,setError]=useState(''),[existing,setExisting]=useState('');
 const attempt=useRef<unknown>(null);
 function update<K extends keyof Content>(key:K,value:Content[K]){setContent({...content,[key]:value});}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setExisting('');if(!uncertain)attempt.current={id:lead?.id||null,revision:lead?.revision||0,request_key:crypto.randomUUID(),source_url:url,source_kind:kind,content};try{const r=await api('',attempt.current);attempt.current=null;setUncertain(false);await onSaved(r.lead.id);}catch(e){const x=e as Error&{status?:number;uncertain?:boolean;existing_id?:string};setError(x.message);setExisting(x.existing_id||'');setUncertain(x.uncertain??!x.status);}finally{setBusy(false);}}
 async function findJobs(){setBusy(true);setError('');try{setJobs((await api('/jobs?q='+encodeURIComponent(jobQuery))).jobs);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const field=(key:'title'|'employer'|'location'|'original_url'|'identity_url',name:string,max:number,required=false)=><label>{name}<input required={required} type={key.endsWith('url')?'url':'text'} maxLength={max} value={content[key]} onChange={e=>update(key,e.target.value)}/></label>;
 return <form className="discovery-form" onSubmit={save}><h3>{lead?'Review this lead':'Retain a new sourcing lead'}</h3><p>Use public recruiting material only. Leave uncertain dates blank. These records do not publish jobs or certify independent review.</p>
  <fieldset disabled={busy||uncertain}><legend>Source and observation</legend><div className="discovery-grid"><label>Source type<select disabled={!!lead} value={kind} onChange={e=>setKind(e.target.value)}>{Object.entries(DISCOVERY_KINDS).map(([key,name])=><option value={key} key={key}>{name}</option>)}</select></label><label>Individual source link<input type="url" required maxLength={1500} disabled={!!lead} value={url} onChange={e=>setUrl(e.target.value)}/></label>{field('title','Role or lead title',180,true)}{field('employer','Employer name, if established',160)}{field('location','Location, if established',160)}<DateInput label="Source observed at (your local time)" value={content.observed_at} onChange={v=>update('observed_at',v||'')} required/></div><label>Exact sponsorship wording, if present<textarea maxLength={1000} value={content.quote} onChange={e=>update('quote',e.target.value)} placeholder="Copy the relevant words; a post’s claim remains unverified until checked against the employer."/></label></fieldset>
  <fieldset disabled={busy||uncertain}><legend>Original employer evidence</legend><div className="discovery-grid">{field('original_url','Original employer application link',1500,content.state==='linked')}{field('identity_url','Employer identity evidence link',1500,content.state==='linked')}</div><label>Employer identity evidence<textarea maxLength={1500} required={content.state==='linked'} value={content.identity_note} onChange={e=>update('identity_note',e.target.value)} placeholder="Explain the legal employer, original careers page and relevant sponsor-register match. A licence alone does not mean this role offers sponsorship."/></label><details><summary>Posting date and closing date evidence</summary><div className="discovery-grid"><DateInput label="Original posting time, only if known" value={content.posted_at} onChange={v=>update('posted_at',v)}/><label>Posting-date source wording<textarea maxLength={500} value={content.posted_evidence} onChange={e=>update('posted_evidence',e.target.value)}/></label><DateInput label="Closing time, only if known" value={content.deadline} onChange={v=>update('deadline',v)}/><label>Closing-date source wording<textarea maxLength={500} value={content.deadline_evidence} onChange={e=>update('deadline_evidence',e.target.value)}/></label></div><p className="fine-print">Search crawl time, last edit and first observation are not original posting dates.</p></details></fieldset>
  <fieldset disabled={busy||uncertain}><legend>Decision and next action</legend><div className="discovery-grid"><label>Decision<select value={content.state} onChange={e=>{const next=e.target.value;setContent({...content,state:next,job_id:next==='linked'?content.job_id:null,duplicate_of:next==='duplicate'?content.duplicate_of:null,follow_up_at:['pending','held'].includes(next)?content.follow_up_at||new Date(Date.now()+3*86400000).toISOString():null});}}>{Object.entries(DISCOVERY_STATES).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label><label>How this review was recorded<select value={content.method} onChange={e=>update('method',e.target.value)}><option value="agent_assisted">Agent-assisted through owner account</option><option value="owner_recorded">Owner-recorded</option></select></label>{['pending','held'].includes(content.state)&&<DateInput label="Review again by (within 30 days)" value={content.follow_up_at} onChange={v=>update('follow_up_at',v)} required/>}</div>
   {content.state==='linked'&&<div className="discovery-job-select"><label>Find an existing published role<input maxLength={120} value={jobQuery} onChange={e=>setJobQuery(e.target.value)}/></label><button className="secondary-button" type="button" onClick={()=>void findJobs()} disabled={jobQuery.trim().length<2}>Find published jobs</button><label>Matching job<select required value={content.job_id||''} onChange={e=>{const job=jobs.find(j=>j.id===e.target.value);setContent({...content,job_id:job?.id||null,...(job?{employer:job.company,original_url:job.apply_url}:{})});}}><option value="">Choose a current role</option>{lead?.content.job_id&&!jobs.some(j=>j.id===lead.content.job_id)&&<option value={lead.content.job_id}>{lead.job_proof?.company} · {lead.job_proof?.title} (previous link)</option>}{jobs.map(j=><option key={j.id} value={j.id}>{j.company} · {j.title} · {j.sponsorship.replaceAll('_',' ')}</option>)}</select></label><p className="fine-print">Selecting a job fills its employer and original link. Check those facts against the source. Saving compares the full retained job evidence; it does not add or refresh a vacancy.</p></div>}
   {content.state==='duplicate'&&<label>Earlier lead ID<input required value={content.duplicate_of||''} onChange={e=>update('duplicate_of',e.target.value)} placeholder="Copy the retained ID from the earlier lead" maxLength={36}/></label>}
   <label>Decision reason and evidence still needed<textarea required minLength={30} maxLength={2000} value={content.reason} onChange={e=>update('reason',e.target.value)}/></label>
  </fieldset>
  {lead&&<p className="fine-print">Lead ID: {lead.id} · Revision {lead.revision}. Saving adds a new decision and preserves every earlier one.</p>}
  {error&&<p role="alert" className="career-error">{error}</p>}{existing&&<button type="button" className="secondary-button" onClick={()=>void onOpen(existing)}>Open the existing lead</button>}{uncertain&&<p role="status">The save is unconfirmed. Retry sends the identical request to avoid duplicate history. Inspect the queue before starting a different review.</p>}
  <div className="discovery-actions"><button className="primary-button" disabled={busy}>{busy?'Saving…':uncertain?'Retry the same save':'Save review record'}</button><button type="button" className="secondary-button" disabled={busy} onClick={onClose}>Close review</button></div>
 </form>;
}
