import React from 'react';
type Run={day:string;run_id:string;state:string;reason:string;started_at:string;finished_at:string|null;retained:number;inspected:number;requests:number;reserved_requests:number;search_pages:number};
export type DiscoveryScoutHealth={enabled:boolean;latest:Run|null;runs:Run[];items:{source_url:string;state:string;reason:string;lead_id:string|null;evidence:{title?:string;employer?:string;sponsorship_quote?:string;deadline?:string;body_sha256?:string}}[];attribution:string;terms:string};
const stamp=(s:string)=>new Date(s).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'});
const reason=(s:string)=>({daily_lead_allowance_used:'Today’s five new-lead allowance has already been used. No source requests were made.',daily_request_allowance_used:'The shared source-request allowance is used. No extra requests were made.',bounded_search_finished:'The bounded source search finished. Candidates await review.',no_new_candidates_in_checked_pages:'No new eligible candidates in the search pages checked.',searching:'The source check is in progress.'} as Record<string,string>)[s]||s.replaceAll('_',' ');
export function DiscoveryScoutStatus({health}:{health?:DiscoveryScoutHealth}){
 if(!health)return null;
 const run=health.latest;
 return <section className="business-supervision" aria-labelledby="discovery-scout-heading">
  <div className="business-section-heading"><h3 id="discovery-scout-heading">New employer discovery</h3><span>{health.enabled?'Daily education scout':'Discovery paused'}</span></div>
  <p>Searches Department for Education Teaching Vacancies for new schools and colleges. Each candidate needs an individual advert with explicit Skilled Worker sponsorship wording and a future closing date.</p>
  {run?<><p><strong>{run.retained} private candidates retained</strong> · {run.inspected} original adverts checked · {run.search_pages} search pages checked</p><p>{reason(run.reason)}</p><p className="business-fine">{run.state==='uncertain'?'Previous execution outcome needs inspection':run.state.replaceAll('_',' ')} · {stamp(run.finished_at||run.started_at)} · {run.requests} requests started / {run.reserved_requests} reserved</p></>:<p className="business-fine">Waiting for its first eligible hourly business run. No automated discovery outcome is recorded yet.</p>}
  {health.items.map(item=><details key={item.source_url}><summary>{item.evidence.title||'Original advert check'} · {item.state}</summary>{item.evidence.employer&&<p>{item.evidence.employer}</p>}{item.evidence.sponsorship_quote&&<blockquote>{item.evidence.sponsorship_quote}</blockquote>}<p>{reason(item.reason)}</p>{item.evidence.deadline&&<p>Advert closing time: {stamp(item.evidence.deadline)}</p>}<a href={item.source_url} target="_blank" rel="noopener noreferrer">Read the original advert</a>{item.lead_id&&<p className="business-fine">Retained in the Discovery queue · {item.lead_id}</p>}</details>)}
  <p className="business-fine">At most two new education candidates per UTC day, within the existing five-new-lead allowance. At most two search pages and four source requests, within the shared source budget. Partial coverage: this does not search all employers or LinkedIn. It does not publish jobs, verify employer licences or promise eligibility.</p>
  <p className="business-fine">{health.attribution} <a href="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/" target="_blank" rel="noopener noreferrer">Licence</a> · <a href={health.terms} target="_blank" rel="noopener noreferrer">Source terms</a></p>
  {!!health.runs.length&&<details><summary>Discovery execution history</summary>{health.runs.map(r=><p key={r.day}>{r.day} · {r.state} · {r.retained} retained · {reason(r.reason)}</p>)}</details>}
 </section>;
}
