import React,{useEffect,useState} from 'react';
import {BrainCircuit,PenLine,ShieldCheck,Pause,Play,RefreshCw} from 'lucide-react';
type Stage={name:string;role:string;state:string;output:{reason?:string;failure?:string;segments?:{text:string;quote:string}[];checks?:{index:number;label?:string;supported:boolean;reason:string;evidence?:{source_id:string;quote:string}[]}[]}|null};
type Run={id:string;day:string;state:string;created_at:string;finished_at:string|null;calls:number;result:{reason?:string;proposed_slot?:string;review_scope?:string}|null;context:{candidates:unknown[];unavailable:string[];existing_review?:{scope:string}|null;existing_review_unavailable?:string|null}|null};
type Data={enabled:boolean;business_enabled:boolean;models:{writer:{model:string};reviewer:{model:string}};opportunities?:{ready:number;held:number;scope:string;items:{title:string;url:string;expires_at:string;wording:string}[]};budget:{runs:number;calls:number;run_limit:number;call_limit:number};runs:Run[];steps:Stage[]};
const label=(s:string)=>({held:'Held for a reason',no_post:'No post needed',reviewed:'Draft reviewed',queued:'Queued',running:'Working',failed:'Stopped'}[s]||s.replaceAll('-',' '));
async function api(path='',body?:unknown){const r=await fetch('/api/admin/marketing/agents'+path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const result=await r.json();if(!r.ok)throw Error(result.error||'Agent records could not load.');return result;}
export function MarketingAgents(){
 const[data,setData]=useState<Data|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function load(){try{setData(await api());setError('');}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void load();const timer=setInterval(()=>{if(!document.hidden)void load();},20000);return()=>clearInterval(timer);},[]);
 async function act(path:string,body:unknown){setBusy(true);setMessage('');try{const r=await api(path,body);setMessage(path==='/run'?`${label(r.state)}. ${r.reason||r.message||'The recorded result will appear below.'}`:body&&path==='/settings'?'Saved. A pause stops the next agent step; resuming does not reset today’s allowance.':'Saved.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const latest=data?.runs[0],today=new Date().toISOString().slice(0,10),attempted=data?.runs.some(r=>r.day===today),active=data?.runs.some(r=>['queued','running'].includes(r.state));
 return <section className="marketing-agent-panel" aria-labelledby="marketing-agents-heading">
  <div className="business-head"><div><p className="business-eyebrow">Plan · write · challenge</p><h3 id="marketing-agents-heading">Editorial agents</h3><p>One daily attempt, using checked guides and eligible vacancy evidence. Every paragraph needs support.</p></div><div className="business-actions"><button aria-label="Refresh editorial agents" onClick={()=>void load()}><RefreshCw size={15}/></button>{data&&<button disabled={busy} onClick={()=>void act('/settings',{enabled:!data.enabled})}>{data.enabled?<Pause size={15}/>:<Play size={15}/>} {data.enabled?'Pause agents':'Resume agents'}</button>}</div></div>
  <div className="marketing-agent-roles">{[[BrainCircuit,'Planner','Chooses a useful, fresh idea or decides not to post. Checks recorded queue space and duplication.'],[PenLine,'Writer','Writes sourced guides with at most one revision. Vacancy cards use fixed facts and retain exact employer wording.'],[ShieldCheck,'Independent reviewer','A different model challenges every paragraph. Unsupported or stale work is held.']].map(([Icon,title,description])=>{const Component=Icon as typeof BrainCircuit;return <article key={title as string}><Component size={21}/><h4>{title as string}</h4><p>{description as string}</p></article>;})}</div>
  {error&&<p className="career-error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
  {!data?<p>Loading editorial agents…</p>:<>
   <div className="marketing-agent-status"><div><strong>{!data.enabled?'Agents paused':!data.business_enabled?'Business operations paused':latest?label(latest.state):'Ready for the first daily check'}</strong><p>{latest?.result?.reason||'The cloud checks once per UTC day through the hourly business workflow. No post is sent by these agents.'}</p></div><button disabled={busy||!data.enabled||!data.business_enabled||active||attempted} onClick={()=>void act('/run',{})}>Run today’s check</button></div>
   <p className="business-fine">{data.budget.runs}/{data.budget.run_limit} shared agent attempts · {data.budget.calls}/{data.budget.call_limit} reserved model calls today (UTC). Guides use at most five calls per attempt; vacancy cards use a planner and reviewer, with no rewriting call. Failures count; an uncertain call is not retried. The allowance resets at 00:00 UTC, and the next hourly check is at :45.</p>
   <p className="business-fine">When a company publishing slot is available, the unchanged Instagram welcome gets one independent review of its caption, registered artwork text and accessibility description. Evidence is refreshed in a new version. Your edits and holds are preserved. The reviewer does not see image pixels.</p>
   <section aria-labelledby="opportunities-editor-heading"><h4 id="opportunities-editor-heading">Opportunities editor</h4>
    <p>{data.opportunities?.ready??0} vacancy candidates ready for planning · {data.opportunities?.held??0} sampled candidates held by evidence checks.</p>
    <p className="business-fine">Requires current employer wording, reviewed licence evidence and a matching application-page check. The planner can choose one candidate only if a publishing slot fits before its evidence expires. A licence alone is insufficient.</p>
    {data.opportunities?.items.map(item=><details className="marketing-agent-detail" key={item.url}><summary>{item.title}</summary><p>{item.wording}</p><p>Evidence expires {new Date(item.expires_at).toLocaleString('en-GB')}.</p><a href={item.url} target="_blank" rel="noreferrer">Read vacancy evidence</a></details>)}
    <p className="business-fine">Vacancy cards preserve the exact role, employer quotation and limitations; the reviewer sees the complete retained advert. A rejected card is held. Changed drafts lose approval. An external schedule requires action at its provider; a local hold cannot cancel it.</p>
   </section>
   <p className="business-fine">Drafts stay in this desk. A model review can be wrong. Live job promotion still requires fresh checks at the provider before scheduling and delivery. Provider delivery, legal-change articles, new artwork and performance learning are not automated by this release.</p>
   {latest&&<details className="marketing-agent-detail"><summary>Latest run evidence · {latest.calls} model calls</summary><p>{latest.id} · {label(latest.state)}</p>{latest.context&&<p>{latest.context.candidates.length} eligible topics · {latest.context.unavailable.length} sources unavailable or changed</p>}{latest.context?.existing_review_unavailable&&<p>{latest.context.existing_review_unavailable}</p>}{(latest.result?.review_scope||latest.context?.existing_review?.scope)&&<p>{latest.result?.review_scope||latest.context?.existing_review?.scope}</p>}{data.steps.length?data.steps.map(s=><div className="marketing-agent-step" key={s.name}><strong>{s.name.replaceAll('-',' ')} · {s.state}</strong>{(s.output?.reason||s.output?.failure)&&<p>{s.output.reason||s.output.failure}</p>}{s.output?.segments?.map((p,i)=><blockquote key={i}>{p.text}<small>Source quote: {p.quote}</small></blockquote>)}{s.output?.checks?.map(c=><div key={c.index}><p><strong>{c.label||'Paragraph '+(c.index+1)}: {c.supported?'supported':'needs correction'}</strong> — {c.reason}</p>{c.evidence?.map((e,i)=><blockquote key={i}>{e.quote}<small>{e.source_id}</small></blockquote>)}</div>)}</div>):<p>No model calls are recorded for this attempt.</p>}</details>}
   <details className="marketing-agent-detail"><summary>Models and recent runs</summary><p className="business-fine">Planner/writer: {data.models.writer.model}<br/>Reviewer: {data.models.reviewer.model}</p>{data.runs.map(r=><p key={r.id}>{r.day} · {label(r.state)} · {r.calls} calls{r.result?.reason?' · '+r.result.reason:''}</p>)}</details>
  </>}
 </section>;
}
