import React,{useEffect,useState} from 'react';
import {BrainCircuit,PenLine,ShieldCheck,Pause,Play,RefreshCw} from 'lucide-react';
type Stage={name:string;role:string;state:string;output:{reason?:string;failure?:string;segments?:{text:string;quote:string}[];checks?:{index:number;supported:boolean;reason:string}[]}|null};
type Run={id:string;day:string;state:string;created_at:string;finished_at:string|null;calls:number;result:{reason?:string;proposed_slot?:string}|null;context:{candidates:unknown[];unavailable:string[]}|null};
type Data={enabled:boolean;business_enabled:boolean;models:{writer:{model:string};reviewer:{model:string}};budget:{runs:number;calls:number;run_limit:number;call_limit:number};runs:Run[];steps:Stage[]};
const label=(s:string)=>({held:'Held for a reason',no_post:'No post needed',reviewed:'Draft reviewed',queued:'Queued',running:'Working',failed:'Stopped'}[s]||s.replaceAll('-',' '));
async function api(path='',body?:unknown){const r=await fetch('/api/admin/marketing/agents'+path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const result=await r.json();if(!r.ok)throw Error(result.error||'Agent records could not load.');return result;}
export function MarketingAgents(){
 const[data,setData]=useState<Data|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function load(){try{setData(await api());setError('');}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void load();const timer=setInterval(()=>{if(!document.hidden)void load();},20000);return()=>clearInterval(timer);},[]);
 async function act(path:string,body:unknown){setBusy(true);setMessage('');try{const r=await api(path,body);setMessage(path==='/run'?`${label(r.state)}. ${r.reason||r.message||'The recorded result will appear below.'}`:body&&path==='/settings'?'Saved. A pause stops the next agent step; resuming does not reset today’s allowance.':'Saved.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const latest=data?.runs[0],today=new Date().toISOString().slice(0,10),attempted=data?.runs.some(r=>r.day===today),active=data?.runs.some(r=>['queued','running'].includes(r.state));
 return <section className="marketing-agent-panel" aria-labelledby="marketing-agents-heading">
  <div className="business-head"><div><p className="business-eyebrow">Plan · write · challenge</p><h3 id="marketing-agents-heading">Editorial agents</h3><p>One daily attempt, using checked public guides. Every paragraph needs evidence.</p></div><div className="business-actions"><button aria-label="Refresh editorial agents" onClick={()=>void load()}><RefreshCw size={15}/></button>{data&&<button disabled={busy} onClick={()=>void act('/settings',{enabled:!data.enabled})}>{data.enabled?<Pause size={15}/>:<Play size={15}/>} {data.enabled?'Pause agents':'Resume agents'}</button>}</div></div>
  <div className="marketing-agent-roles">{[[BrainCircuit,'Planner','Chooses a useful, fresh idea or decides not to post. Checks recorded queue space and duplication.'],[PenLine,'Writer','Drafts two to four paragraphs, each tied to a source quote. Gets one revision at most.'],[ShieldCheck,'Independent reviewer','A different model challenges every paragraph. Unsupported or stale work is held.']].map(([Icon,title,description])=>{const Component=Icon as typeof BrainCircuit;return <article key={title as string}><Component size={21}/><h4>{title as string}</h4><p>{description as string}</p></article>;})}</div>
  {error&&<p className="career-error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
  {!data?<p>Loading editorial agents…</p>:<>
   <div className="marketing-agent-status"><div><strong>{!data.enabled?'Agents paused':!data.business_enabled?'Business operations paused':latest?label(latest.state):'Ready for the first daily check'}</strong><p>{latest?.result?.reason||'The cloud checks once per UTC day through the hourly business workflow. No post is sent by these agents.'}</p></div><button disabled={busy||!data.enabled||!data.business_enabled||active||attempted} onClick={()=>void act('/run',{})}>Run today’s check</button></div>
   <p className="business-fine">{data.budget.runs}/{data.budget.run_limit} shared research and marketing attempts · {data.budget.calls}/{data.budget.call_limit} reserved model calls today (UTC). Marketing uses at most five calls per attempt. Failures count; an uncertain call is not retried. The allowance resets at 00:00 UTC, and the next hourly check is at :45.</p>
   <p className="business-fine">Drafts stay in this desk. A model review can be wrong. Provider delivery, fresh job promotion, legal-change articles, artwork and performance learning are not automated by this release.</p>
   {latest&&<details className="marketing-agent-detail"><summary>Latest run evidence · {latest.calls} model calls</summary><p>{latest.id} · {label(latest.state)}</p>{latest.context&&<p>{latest.context.candidates.length} eligible guides · {latest.context.unavailable.length} sources unavailable or changed</p>}{data.steps.length?data.steps.map(s=><div className="marketing-agent-step" key={s.name}><strong>{s.name.replaceAll('-',' ')} · {s.state}</strong>{(s.output?.reason||s.output?.failure)&&<p>{s.output.reason||s.output.failure}</p>}{s.output?.segments?.map((p,i)=><blockquote key={i}>{p.text}<small>Source quote: {p.quote}</small></blockquote>)}{s.output?.checks?.map(c=><p key={c.index}><strong>Paragraph {c.index+1}: {c.supported?'supported':'needs correction'}</strong> — {c.reason}</p>)}</div>):<p>No model calls are recorded for this attempt.</p>}</details>}
   <details className="marketing-agent-detail"><summary>Models and recent runs</summary><p className="business-fine">Planner/writer: {data.models.writer.model}<br/>Reviewer: {data.models.reviewer.model}</p>{data.runs.map(r=><p key={r.id}>{r.day} · {label(r.state)} · {r.calls} calls{r.result?.reason?' · '+r.result.reason:''}</p>)}</details>
  </>}
 </section>;
}
