import React,{useEffect,useRef,useState} from 'react';
type Delivery={id:string;kind:string;state:string;critical_count:number;high_count:number;source_run:string|null;created_at:string;message_id:string|null;received_at:string|null};
type Status={enabled:boolean;revision:number|null;destination:string|null;verified:boolean;available:boolean;address_changed:boolean;pending:string|null;deliveries:Delivery[];last_scan:{checked_at:string;accepted:number;held:number}|null};
const stamp=(x:string)=>new Date(x).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'});
const labels:Record<string,string>={reserved:'Send reserved — outcome not confirmed',uncertain:'Delivery uncertain — further mail held',accepted:'Accepted by email service',confirmed:'Receipt confirmed by owner',cancelled:'Cancelled before sending'};
async function api(path='',body?:unknown){const r=await fetch('/api/admin/business/alerts'+path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const value=await r.json();if(!r.ok)throw Error(value.error||'Alerts could not load.');return value;}
export function OperationAlerts(){
 const[data,setData]=useState<Status|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),sequence=useRef(0);
 async function load(){const seq=++sequence.current;try{const next=await api();if(seq===sequence.current){setData(next);setError('');}}catch(e){if(seq===sequence.current){setData(null);setError((e as Error).message);}}}
 useEffect(()=>{void load();const timer=setInterval(()=>{if(!document.hidden)void load();},30000);return()=>{clearInterval(timer);sequence.current++;};},[]);
 async function act(path:string,body:unknown){setBusy(true);setError('');setMessage('');try{const result=await api(path,body);setMessage(path==='/test'?result.state==='accepted'?'The email service accepted the test. Check your Inbox and Spam, then confirm the matching receipt below.':`Test ${result.state}. Check the delivery record before another attempt.`:path==='/received'?'Your receipt confirmation was recorded.':'Alert preference saved.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section id="operation-alerts" className="business-supervision operation-alerts" aria-labelledby="operation-alerts-heading">
  <div className="business-section-heading"><h3 id="operation-alerts-heading">Failure & recovery alerts</h3><span>Private · owner only</span></div>
  <p>Receive a short email when critical or high-priority findings change, and when reported findings clear. No CVs, customer messages or personal analytics are included.</p>
  {error&&<p role="alert" className="career-error">{error}</p>}{message&&<p role="status">{message}</p>}
  {data?<>
   <label className="operation-alert-toggle"><input type="checkbox" checked={data.enabled} disabled={busy||(!data.enabled&&(!data.verified||!data.available))} onChange={e=>void act('/settings',{enabled:e.target.checked,revision:data.revision})}/>Email operational alerts to my verified owner address</label>
   <p className="business-fine">{data.destination||'Verify your owner email before enabling alerts.'}{data.address_changed?' · Address changed: switch alerts off and on to confirm this destination.':''}{!data.available?' · Email service unavailable.':''}</p>
   {data.pending&&<p className="operation-alert-warning">Further mail is held because a send has no confirmed outcome. Check your Inbox, Spam and provider logs. Only confirm receipt below if you actually received that message. Turning alerts off does not recall mail already handed to the provider.</p>}
   <div className="business-actions"><button disabled={busy||!data.enabled||!data.available||!data.verified||!!data.pending||data.address_changed} onClick={()=>void act('/test',{revision:data.revision})}>Send one test email</button><button disabled={busy} onClick={()=>void load()}>Refresh alert receipts</button></div>
   <p className="business-fine">Checked every 15 minutes using the latest hourly findings; also checks whether business operations stopped or became overdue. Up to four emails per owner per UTC day, including one test; unchanged incidents are reminded at most daily. Pausing business operations pauses automatic mail. {data.last_scan?'Last alert scan: '+stamp(data.last_scan.checked_at)+'.':'No scheduled alert scan recorded yet.'}</p>
   <p className="business-fine">Provider acceptance does not prove inbox delivery. These checks share Cloudflare with the site and cannot independently detect a complete provider outage; the separate Codex check depends on its local scheduler and access.</p>
   {data.deliveries.length?<div className="operation-alert-receipts">{data.deliveries.map(d=><details key={d.id}><summary><strong>{d.kind==='test'?'Connection test':d.kind==='recovery'?'Reported findings cleared':'Incident alert'}</strong> · {labels[d.state]||d.state}<br/><small>{stamp(d.created_at)}</small></summary><p>{d.critical_count} critical · {d.high_count} high-priority findings</p><p>Receipt: {d.id}</p>{d.message_id&&<p>Email service receipt: {d.message_id}</p>}{d.source_run&&<p>Source run: {d.source_run}</p>}{d.received_at?<p>You confirmed receipt at {stamp(d.received_at)}.</p>:d.state!=='cancelled'&&<button disabled={busy} onClick={()=>void act('/received',{id:d.id})}>I received this exact email</button>}</details>)}</div>:<p className="business-fine">No email attempts recorded. Enabling alerts does not send a welcome email.</p>}
  </>:!error&&<p>Loading alert settings…</p>}
 </section>;
}
